server:
  port: 9001
spring:
  application:
    name: user-auth
  redis:
    host: 192.168.137.166
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.137.166:3306/changgou_user?useUnicode=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
  main:
    allow-bean-definition-overriding: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka
auth:
  ttl: 3600  #token存储到redis的过期时间
  clientId: changgou
  clientSecret: changgou
  cookieDomain: localhost
  cookieMaxAge: -1
encrypt:
  key-store:
    location: classpath:/changgou.jks
    secret: changgou
    alias: changgou
    password: changgou