server:
  port: 18085
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
spring:
  thymeleaf:
    cache: false
  application:
    name: item
  main:
    allow-bean-definition-overriding: true
# 生成静态页的位置
pagepath: E:\Java_project\springCloud_Shop\changgou_parent\changgou_web\changgou-web-item\src\main\resources\templates\items
